baseURL = 'https://flyyyy-fly.github.io/'
languageCode = 'zh-cn'
title = '我' 
theme = "PaperMod"

# 1. 设置顶层作者
[author]
    name = "flyyyy-fly"

[params]
    env = "production"
    author = "flyyyy-fly" 
    
    defaultTheme = "auto" 
    ShowReadingTime = true
    ShowFullTextContent = false 
    showCodeCopyButtons = true

    [params.homeInfoParams]
        Title = "你好，欢迎来到我的频道 "
        Content = "在这里记录我的学习。"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/flyyyy-fly"
    [[params.socialIcons]]
        name = "email"
        url = "mailto:18091655636@163.com"

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "文章"
        url = "/posts/"
        weight = 10
    [[menu.main]]
        identifier = "archives"
        name = "归档"
        url = "/archives/"
        weight = 20
    [[menu.main]]
        identifier = "tags"
        name = "标签"
        url = "/tags/"
        weight = 30
    [[menu.main]]
        identifier = "search"
        name = "搜索"
        url = "/search/"
        weight = 40

# 2. 核心补丁：告诉 Hugo 渲染文章时忽略那个出错的 RSS 文件
[outputs]
    home = ["HTML"]    # 去掉 "RSS"，这样就不生成 rss.xml，彻底避开报错
    page = ["HTML"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    lineNos = false

[minify]
  disableHTML = true
  disableXML = true
